# Generated by Django 3.1.5 on 2021-02-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20210208_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='url_link',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
