# Generated by Django 3.1.5 on 2021-01-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_emailconfirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstripe',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
