# Generated by Django 3.1.5 on 2021-02-08 16:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_useraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='address',
            new_name='alamat',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='address2',
            new_name='alamat2',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='postal_code',
            new_name='kode_pos',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='city',
            new_name='kota',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='country',
            new_name='negara',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='state',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='provinsi',
            field=models.CharField(blank=True, choices=[('ACE', 'Aceh'), ('BLI', 'Bali'), ('BTN', 'Banten'), ('BKL', 'Bengkulu'), ('DIY', 'Yogyakarta'), ('JKT', 'Jakarta'), ('GOR', 'Gorontalo'), ('JMB', 'Jambi'), ('JBR', 'Jawa Barat'), ('JTG', 'Jawa Tengah'), ('JTM', 'Jawa Timur'), ('KBR', 'Kalimantan Barat'), ('KSL', 'Kalimantan Selatan'), ('KTG', 'Kalimantan Tengah'), ('KTM', 'Kalimantan Timur'), ('KTR', 'Kalimantan Utara'), ('BBL', 'Kepulauan Bangka-Belitung'), ('KRI', 'Kepulauan Riau'), ('LPG', 'Lampung'), ('MLK', 'Maluku'), ('MUT', 'Maluku Utara'), ('NTB', 'Nusa Tenggara Barat'), ('NTT', 'Nusa Tenggara Timur'), ('PPA', 'Papua'), ('PPB', 'Papua Barat'), ('RIU', 'Riau'), ('SLB', 'Sulawesi Barat'), ('SLS', 'Sulawesi Selatan'), ('SLT', 'Sulawesi Tengah'), ('SLR', 'Sulawesi Tenggara'), ('SLU', 'Sulawesi Utara'), ('SMB', 'Sumatera Barat'), ('SMS', 'Sumatera Selatan'), ('SMU', 'Sumatera Utara')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
