"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
#import os perlu jika menggunakan os.path.join() dan os.path.dirname()
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR adalah lokasi dari C:\ecommerce_2\ecommerce. BASE_DIR juga disebut sebagai root.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'pz#fftmkgva&71rg-tv&8%2ie90(%gt=vdxsc3w%nwyje!q(5n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['http://127.0.0.1:4040 ', '70dffc944620.ngrok.io']

# Send Email for Activation

DEFAULT_FROM_EMAIL = 'Fahmi Aneka Flora <fahmianekaflora@gmail.com>'

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'fahmianekaflora@gmail.com'
EMAIL_HOST_PASSWORD = 'vedder1234'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

SITE_URL = 'http://anekaflora.com'
if DEBUG:
    SITE_URL = 'http://127.0.0.1:8000'
    
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    #apps yang baru dibuat harus di tulis di 'installed apps'
    'accounts.apps.AccountsAppConfig',
    'carts',
    'marketing',
    'orders',
    'products',
    'localflavor',
    'phonenumber_field',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'marketing.middleware.DisplayMarketing',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #TEMPLATES_DIRS, direktori untuk menyimpan file-file templates
        #lokasinya di C:\ecommerce_2\ecommerce\templates
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

#untuk mengubah timezone, install pytz (python timzones),
#buka shell python, import pytz, 
# run command: for items in pytz.all_timezones:
#                   print(items)
#lalu akan muncul semua timezone yang ada di pytz.
TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_L10N = True

USE_TZ = True

MARKETING_HOURS_OFFSET = 3
MARKETING_SECONDS_OFFSET = 0

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static", "media")
# MEDIA_ROOT = 'C:\ecommerce_2\static\media'
#static_root, adalah direktori penyimpanan utama, ketika collectstatic, data akan tersimpan di static_root
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static", "static_root")
#ketika running collectstatic akan mengumpulkan data dari direktori static_files ke direktori static_root 
#os.path.join() berfungsi untuk menggabungkan 2 direktori di dalam 1 path direktori berdasarkan sistem operasi
#os.path.dirname(BASE_DIR) berfungsi untuk mengidentifikasi lokasi base_dir dengan nama direktorinya.
#sehingga dengan begitu penggabungan 'static' dan 'static_files' berada diluar base_dir, tidak di dalam base_dir.
#jika hanya BASE_DIR, maka penggabungannya akan terjadi di dalam direktori BASE_DIR.
STATICFILES_DIRS = [
    os.path.join(os.path.dirname(BASE_DIR), "static", "static_files")
] 

STRIPE_SECRET_KEY = 'sk_test_51HzBDPJvQPHLTxRnggI2Awpkq8hqHLDgB0FzFmL2s2FS39DomvhkkZPk8tddT1YAXaPh4qQ8e9SnfKpP5s0mZpGk00Ojo43aGu'
STRIPE_PUBLISHABLE_KEY = 'pk_test_51HzBDPJvQPHLTxRn28x7KBZIXJ2pws6Acxwu0hY5IwnLkLJHLze264ZvEfyExKuRMEZ6u8r9x7DOXVYGq23pj1Fa003bht4Iu1'

MIDTRANS_CLIENT_KEY = 'SB-Mid-client-OgPmIuHFDCH6Yest'
MIDTRANS_SERVER_KEY = 'SB-Mid-server-VNOvupORphJBAElh8JR7H9y1'